import { Controller, Get, Response } from '@nestjs/common';
import moment from 'moment';
import momentJalaali from 'moment-jalaali';
import { createCanvas } from 'canvas';
import { Response as ExpressResponse } from 'express';

@Controller('get')
export class GetController {

  @Get('time')
  getTime() {
    const time = {
      gregorian: this.getGregorianTime(),
      shamsi: this.getShamsiTime(),
    };

    return time;
  }

  @Get('image')
  async getImage(@Response() res: ExpressResponse) {
    const time = {
      gregorian: this.getGregorianTime(),
      shamsi: this.getShamsiTime(),
    };

    const canvas = createCanvas(800, 600);
    const ctx = canvas.getContext('2d');

    const gradient = ctx.createLinearGradient(0, 0, 0, canvas.height);
    gradient.addColorStop(0, '#ff7e5f');
    gradient.addColorStop(1, '#feb47b');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.font = '40px Arial, sans-serif';
    ctx.fillStyle = '#fff';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'top';
    ctx.shadowColor = '#555';
    ctx.shadowBlur = 15;
    ctx.fillText('Current Date Information', canvas.width / 2, 30);

    ctx.shadowColor = 'transparent';

    this.drawCard(ctx, 50, 100, 350, 250, 'Gregorian Date', [
      `Date: ${time.gregorian.formatted}`,
      `Year: ${time.gregorian.year}`,
      `Month: ${time.gregorian.monthName}`,
      `Day: ${time.gregorian.day}`,
    ]);

    this.drawCard(ctx, 400, 100, 350, 250, 'Shamsi Date', [
      `Date: ${time.shamsi.formatted}`,
      `Year: ${time.shamsi.year}`,
      `Month: ${time.shamsi.faMonthName}`,
      `Day: ${time.shamsi.day}`,
    ]);

    ctx.strokeStyle = '#fff';
    ctx.beginPath();
    ctx.moveTo(50, 500);
    ctx.lineTo(canvas.width - 50, 500);
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.font = '20px Arial, sans-serif';
    ctx.fillStyle = '#fff';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by 66API', canvas.width / 2, 530);

    res.setHeader('Content-Type', 'image/png');
    canvas.createPNGStream().pipe(res);
  }

  private getGregorianTime() {
    const current = moment();
    return {
      year: current.year(),
      month: current.month() + 1,
      monthName: current.format('MMMM'),
      day: current.date(),
      formatted: current.format('YYYY-MM-DD'),
    };
  }

  private getShamsiTime() {
    const current = momentJalaali();
    const persianMonths = [
      'Farvardin', 'Ordibehesht', 'Khordad', 'Tir', 'Mordad', 'Shahrivar',
      'Mehr', 'Aban', 'Azar', 'Dey', 'Bahman', 'Esfand'
    ];

    const persianMonthsFarsi = [
      'فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور',
      'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'
    ];

    return {
      year: current.jYear(),
      month: current.jMonth() + 1,
      day: current.jDate(),
      monthName: persianMonths[current.jMonth()],
      faMonthName: persianMonthsFarsi[current.jMonth()],
      formatted: current.format('jYYYY/jMM/jDD'),
    };
  }

  private drawCard(ctx, x, y, width, height, title, content) {
    ctx.fillStyle = '#fff';
    ctx.fillRect(x, y, width, height, 20);

    ctx.strokeStyle = '#ff7e5f';
    ctx.lineWidth = 3;
    ctx.strokeRect(x, y, width, height, 20);

    ctx.font = '30px Arial, sans-serif';
    ctx.fillStyle = '#2c3e50';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'top';
    ctx.fillText(title, x + width / 2, y + 10);

    ctx.font = '20px Arial, sans-serif';
    ctx.fillStyle = '#555';
    ctx.textAlign = 'left';
    let contentY = y + 50;
    content.forEach((line, index) => {
      ctx.fillText(line, x + 20, contentY + index * 30);
    });
  }
}
